---
- name: Deploy Translator Pilot Local Pipeline to ThinkPad T14
  hosts: local_thinkpad
  become: no
  vars_files:
    - group_vars/all.yml
    - group_vars/secrets.yml

  roles:
    - translatorpilot
